cd ..
cd dcase2020_task2
conda activate dcase2020_task2


OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=short reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=0 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=short reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=1 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=short reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=2 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=short reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=3 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=1 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=short reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=4 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=1 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=short reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=5 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=1 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=long reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=0 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=1 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=long reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=1 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=long reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=2 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=long reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=3 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=long reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=4 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &
OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2 python -m experiments.sampling_experiment with latent_size=8 learning_rate=0.0001 weight_decay=0.0001 normalize=True feature_context=long reconstruction_class=reconstructions.AUC model_class=models.SamplingFCAE machine_type=5 num_workers=2 -m student2.cp.jku.at:27017:dcase2020_task2_simple_sampling > /dev/null 2>&1 &

wait